[package]
name = "amd-apcb"
version = "0.1.0"
authors = ["Oxide Computer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_io = { version = "0.1.20210325", optional = true }
#
# In order to use macros as discriminants in enums that make use of derive
# macros (e.g., AsBytes, FromPrimitive), we need the syn crate to have "full"
# enabled. The easiest way to do this is to use num-derive's "full-syntax",
# which passes "full" through to syn.
#
byteorder = "1.4.3"
num-derive = { version = "0.3.0", features = [ "full-syntax" ] }
num-traits = { version = "0.2.12", default-features = false }
serde = "1.0.125"
serde_derive = "1.0.125"
zerocopy = "0.5.0"

[features]
default = ["std"]
no_std = ["core_io"]
std = []
