[package]
name = "amd-apcb"
version = "0.1.0"
authors = ["Oxide Computer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_io = { version = "0.1.20210325", optional = true }
ssmarshal = "1.0.0"
serde = "1.0.125"
serde_derive = "1.0.125"

[features]
default = ["std"]
no_std = ["core_io"]
std = []
